-keep class com.android.vending.billing.**
-dontwarn com.anjlab.android.iab.v3.BillingProcessor
-dontwarn com.mikepenz.fastadapter_extensions.items.**
-dontwarn co.metalab.asyncawait.**
-dontwarn com.afollestad.bridge.BasicAuthentication